name: tests

on: push

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: 'true'

      - name: Install deps
        run: go mod download

      - name: Create vendor
        run: |
          cd internal/analyzer/testdata/src/example
          go mod init example.com/test
          go get go.uber.org/zap
          go mod vendor

      - name: Run tests
        run: go test ./internal/analyzer/...